# Generated by Django 4.2.2 on 2023-10-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_taskmodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='images',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='images/'),
        ),
    ]
